server:
  port: 9000
spring:
  application:
    name: ZUUL-APIGATEWAY

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

zuul:
  routes:
    movie:
      path: /movie/**
      url: http://localhost:8080/movie